### ISSUE TITLE
fixes for official r39

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#10]
Offical r39 was recently released, this requires some fixes for the changed kernal routines.
Also requires Prog8 8.0 to compile. (not officially released yet)

I'm making the required changes in the `newr39` branch.

Note that I accidentally committed a change in the main branch which has been reverted again, it was not my intention to directly commit in main. :disappointed:

**Comment by cyborgar** [comment]
Thanks, 

I tried to test with the new emulator and saw that there was a problem with the screen setup. I'll just wait for the new version of prog8 before updating main.

**Comment by irmen** [comment]
I think I'll be releasing it somewhere in the coming days. The two small commits in the newr39 branch seem to be all that's needed  to get Petaxian to run again on r39.

**Comment by irmen** [comment]
prog8 8.0 has been released https://github.com/irmen/prog8/releases/tag/v8.0

**Comment by cyborgar** [comment]
New branch has been merged to main now.

**Comment by irmen** [comment]
Great!  
Note that the new documented keyboard API routines are also exposed in prog8 8.0 but I'm not sure if/how these will help your keyboard control issue in the game.  In any case, that is a separate issue.

**Comment by cyborgar** [comment]
I've had a look at the new keyboard code and it doesn't quite work. The **kbdbuf_get_modifiers** actually works well in the sense that gives flags for currently pressed keys. The peek function does unfortunately not work quite good enough.

**Comment by irmen** [comment]
Yeah I was confused by it as well, it keeps the key in the buffer so you have to use GETIN as well anyway.

I did experiment with the "raw" ps2 key event hook though and that offers a callback for every raw ps2 keypress, including keys such as page up and page down.
