### ISSUE TITLE
compiler errors due to upcoming prog8 bool type

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#12]
Hi, the next prog8 release introduces a 'bool' datatype and several expressions will now yield a boolean result rather than a straight ubyte.
This allows prog8 to generate more optimal code for comparisons, logical operations etc.
However certain existing expressions are no longer allowed. Compiling petaxian with the upcoming compiler gives:

WARN  file:///home/irmen/Projects/Petaxian/enemy.p8:539:5: name 'enemyRef' shadows occurrence at enemy.p8 line 147
WARN  file:///home/irmen/Projects/Petaxian/cx16/keyboard.p8:23:5: return type of the subroutine should probably be bool instead of ubyte
ERROR file:///home/irmen/Projects/Petaxian/enemy.p8:430:11: can't use boolean operand with this operator *
ERROR file:///home/irmen/Projects/Petaxian/enemy.p8:431:11: can't use boolean operand with this operator *
ERROR file:///home/irmen/Projects/Petaxian/explosion.p8:75:17: can't use boolean operand with this operator *
ERROR file:///home/irmen/Projects/Petaxian/explosion.p8:76:17: can't use boolean operand with this operator *

The last four are caused by expressions like this:  (not explosionRef[EX_SUBPOS] & main.TOPMOST) * 4
I think your intent is to write there:  (not explosionRef[EX_SUBPOS] & main.TOPMOST) << 2

The error message is meant to catch silly mistakes of using booleans in arbitrary arithmetic calculations. Bit shifting is okay.

Do you agree with the error message or do you think it is too strong?

**Comment by cyborgar** [comment]
It basically missed the better bit shift here, but that certainly works better than multiplication here.

I'm generally very much in favor of strong typing and having an actual bool is good. This particular lines where partial attempts at efficient/and compact code and not necessarily the most readable. I can certainly live with strict error messages.

Though I'm not completely sure why you would allow bit shift and not multiplication. In both cases the expression in () must be converted to a byte (or word) before the either << or * make sense. I mean if bool isn't convertible to a byte then why would bit shift be a valid operation? 

BTW, if this is just to make sure user know what he is doing a cast could be an option?

**Comment by irmen** [comment]
Yes I edited my comment above, for now the check is not implemented (too much issues)

I like the idea of an option to turn off auto cast but I won't build that any time soon because it will be a huge effort due to the way prog8's type system is currently implemented...

**Comment by irmen** [comment]
I'll close this issue for now.
