### ISSUE TITLE
psg volume too large

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#14]
For 2 sounds in the cx16 sounds module it sets the PSG (max)volume to a value 127 which is out of range, the valid Vera PSG volume range is 0-63

maybe I should document this more clearly in prog8's psg module as well?

**Comment by cyborgar** [comment]
Well, I think it would help to have documentation of the PSG system for Prog8. Though if there is a good document for PSG that can be referenced, the Prog8 doc could probably be fairly rudimentary.

**Comment by irmen** [comment]
I'll see what I can improve there.

**Comment by irmen** [comment]
Yeah I dunno, i found the volume very low in my experiments as well (both emulators). I don't know how the channel mixing is done. I hoped the real hardware had better gain.
Maybe we need to play the same sound over multiple channels to get more gain.... but that's a kludge
