### ISSUE TITLE
three letter symbols behavior in assembly in next prog8 version

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#15]
Hi, the next prog8 version will treat 3-letter symbols differently (it's going to prefix them to avoid name clashes with regular cpu instructions in the resulting assembly code).

This means hand written inlined assembly needs to take this prefixing into account.

In `convert.p8` there's the `tbl` array that will now break because it is referenced as such in some assembly code. May I suggest simply renaming its occurences to `table` to make the code compile again without errors.

In `c64/keyboard.p8` there is `key` which should be renamed to `keypress` or something as well.

**Comment by cyborgar** [comment]
Done.
