### ISSUE TITLE
re upload on X16 forum to make it visible again?

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#16]
Hi, the old Commander X16 forum has moved to https://cx16forum.com/forum/

the old download section is gone but there is a new one replacing it.
Since there have been extensive updates to the roms and the emulator since most of the uploads were done on the old forum, it was decided that the old uploads were moved into an "Archived" section because many were incompatible.

Authors should re upload a new version of their software in the appropriate topic if the software is tested to run fine on new ROMS+emulator.

Unfortunately, Petaxian is still among the archived games:
https://cx16forum.com/forum/viewtopic.php?p=25182&hilit=petaxian#p25182

Would you consider rebuilding a new version of it and re-uploading it on the games topic , so that Petaxian will be easily visible again?

**Comment by cyborgar** [comment]
Thanks for the notification. Though I have been lurking a bit on the new forums I haven't really been paying much attention. I've added Petaxian to the Download page now.
