### ISSUE TITLE
upcoming prog8 version 9 has a few breaking changes

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#17]
I'm busy updating the prog8 compiler to a new major version (9) and with that, there will be some breaking changes. [A guide how to upgrade existing code](https://prog8.readthedocs.io/en/latest/upgrading8.html) is in the prog8 documentation.  This version of the compiler hasn't been released yet but I thought I should give a heads up.

Also for Petaxian I went ahead and created the "prog8v9" branch that will include the necessary changes to make the game compile again with prog8 version 9.   Note that this version can then no longer be compiled with an older version of the compiler.

**Comment by cyborgar** [comment]
I've had a look at the changes and apply them when v9 is released (or just merge in your updates). I have another (very slow moving project) that will need a few of the updates as well.

**Comment by irmen** [comment]
Great stuff

The reason I've went ahead with this branch for Petaxian is that I have always been using Petaxian as a benchmark / test program for new versions of the compiler :)

**Comment by cyborgar** [comment]
I've finally got a round to checking out the newer version of Prog8 and for some reason I ended up doing exactly the same changes as you did :-)

**Comment by irmen** [comment]
the prog8v9 branch can be deleted then as well, I think!
