### ISSUE TITLE
prog8 10.5 changes

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#28]
Prog8 10.5 is going to introduce several breaking changes.

a compilation error issue regarding inline asm , see the Pull request #27 

the compiler got renamed to 'prog8c' and the jar file accordingly  prog8c-10.5-all.jar

**Comment by cyborgar** [comment]
Pull request has been merged. I have seen the some of the discussion about the renaming, though I only check in on discord every now and then. The name change makes sense to me :-)
