### ISSUE TITLE
need to mark a few variables as @shared

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#5]
The upcoming prog8 compiler version will be more aggressive about removing unused variables (in prog8 code)

There are some variables in cx16/joystick.p8 that will have to be marked as ``@shared`` now to avoid assembler errors in the included assembly that refers to them. (prog8 code doesn't refer to them!)

it's the three ``joy_info`` variables at the top of ``cx16/joystick.p8``.

**Comment by cyborgar** [comment]
Updated.

7.3 shaves another 172 bytes from the resulting CX16 prog file (and 153 bytes from the C64 output).

Funny how little such output size reductions would matter on a modern system compared with the importance of gaining half a kilobyte could be for the C64 output.
