### ISSUE TITLE
enemyRef should be forced into Zeropage

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#8]
https://github.com/cyborgar/Petaxian/blob/86b80c3f59fab050bc3e88968f48407358e26bfa/enemy.p8#L116

this should read
``uword @requirezp enemyRef``

because the file contains some assembly code that uses zeropage indirect on the enemyRef pointer.

**Comment by cyborgar** [comment]
Added to my local updates so it will be added to the repo in a few weeks (I estimate). I've been doing a bit of other work as well (refactoring, optimization of enemy.clear function etc).
